# Generated by Django 5.1.7 on 2025-10-24 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('prescription_required', models.BooleanField(default=False, verbose_name='Требуется рецепт')),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='Побочные эффекты')),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='Противопоказания')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Стаж (лет)')),
                ('work_phone', models.CharField(max_length=20, verbose_name='Рабочий телефон')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер лицензии')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отделение')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Часы работы')),
                ('office_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер кабинета')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_templates', to='patients.doctor')),
            ],
            options={
                'verbose_name': 'Шаблон диагноза',
                'verbose_name_plural': 'Шаблоны диагнозов',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Диагноз')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=10, verbose_name='Статус')),
                ('room_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер кабинета')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.doctor', verbose_name='Врач')),
                ('medicines', models.ManyToManyField(blank=True, to='patients.medicine', verbose_name='Лекарства')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(blank=True, null=True, verbose_name='Жалобы пациента')),
                ('anamnesis', models.TextField(blank=True, null=True, verbose_name='Анамнез заболевания')),
                ('objective_data', models.TextField(blank=True, null=True, verbose_name='Объективные данные')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.appointment')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.doctor')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='patients.medicalrecord')),
            ],
            options={
                'verbose_name': 'Заметка врача',
                'verbose_name_plural': 'Заметки врача',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Рост (см)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='Хронические заболевания')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Аллергии')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Группа крови')),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер страховки')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Экстренный контакт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('analysis', 'Анализ'), ('xray', 'Рентген'), ('mri', 'МРТ'), ('ct', 'КТ'), ('ultrasound', 'УЗИ'), ('other', 'Другое')], max_length=20)),
                ('file', models.FileField(upload_to='patient_files/%Y/%m/')),
                ('title', models.CharField(default='Документ', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='patients.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл пациента',
                'verbose_name_plural': 'Файлы пациента',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100, verbose_name='Дозировка')),
                ('frequency', models.CharField(max_length=100, verbose_name='Частота приема')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Дополнительные указания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.medicalrecord')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicine')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='PatientActiveMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, default='', max_length=100, verbose_name='Дозировка')),
                ('frequency', models.CharField(blank=True, default='', max_length=100, verbose_name='Частота')),
                ('duration', models.CharField(blank=True, default='', max_length=100, verbose_name='Длительность')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='Указания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_medicines', to='patients.doctor', verbose_name='Врач')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicine', verbose_name='Препарат')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_medicines', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Активный препарат пациента',
                'verbose_name_plural': 'Активные препараты пациента',
                'unique_together': {('patient', 'doctor', 'medicine')},
            },
        ),
    ]
