# Generated by Django 5.1.7 on 2025-10-21 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_doctor_iin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='office_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(blank=True, null=True, verbose_name='Жалобы пациента')),
                ('anamnesis', models.TextField(blank=True, null=True, verbose_name='Анамнез заболевания')),
                ('objective_data', models.TextField(blank=True, null=True, verbose_name='Объективные данные')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('analysis', 'Анализ'), ('xray', 'Рентген'), ('mri', 'МРТ'), ('other', 'Другое')], max_length=20)),
                ('file', models.FileField(upload_to='patient_files/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='patients.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100, verbose_name='Дозировка')),
                ('frequency', models.CharField(max_length=100, verbose_name='Частота приема')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Дополнительные указания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.medicalrecord')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicine')),
            ],
        ),
    ]
