# Generated by Django 5.1.7 on 2025-10-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicines', to='patients.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicines', to='patients.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medicines', to='patients.prescription')),
            ],
            options={
                'verbose_name': 'Активный препарат пациента',
                'verbose_name_plural': 'Активные препараты пациентов',
                'ordering': ['-prescribed_date'],
                'unique_together': {('patient', 'prescription')},
            },
        ),
    ]
