# Generated by Django 5.1.7 on 2025-10-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientactivemedicine_delete_patientmedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
    ]
