# Generated by Django 5.1.7 on 2025-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_verified_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Секрет для OTP'),
        ),
    ]
