# Generated by Django 5.1.7 on 2025-10-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_iin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_specialty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
