# Generated by Django 5.1.7 on 2025-10-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='iin',
            field=models.CharField(default=11, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
