# Generated by Django 5.1.7 on 2025-10-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_doctor_office_number_medicalrecord_patientfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Медицинская запись', 'verbose_name_plural': 'Медицинские записи'},
        ),
        migrations.AlterModelOptions(
            name='patientfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Файл пациента', 'verbose_name_plural': 'Файлы пациента'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='patientfile',
            name='title',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='file',
            field=models.FileField(upload_to='patient_files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='file_type',
            field=models.CharField(choices=[('analysis', 'Анализ'), ('xray', 'Рентген'), ('mri', 'МРТ'), ('ct', 'КТ'), ('ultrasound', 'УЗИ'), ('other', 'Другое')], max_length=20),
        ),
        migrations.CreateModel(
            name='DiagnosisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_templates', to='patients.doctor')),
            ],
            options={
                'verbose_name': 'Шаблон диагноза',
                'verbose_name_plural': 'Шаблоны диагнозов',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.doctor')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='patients.medicalrecord')),
            ],
            options={
                'verbose_name': 'Заметка врача',
                'verbose_name_plural': 'Заметки врача',
                'ordering': ['-created_at'],
            },
        ),
    ]
