# Generated by Django 5.1.7 on 2025-10-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfile',
            name='title',
            field=models.CharField(default='Документ', max_length=255, verbose_name='Название'),
        ),
    ]
