# Generated by Django 5.1.7 on 2025-10-21 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patientmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientActiveMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, default='', max_length=100, verbose_name='Дозировка')),
                ('frequency', models.CharField(blank=True, default='', max_length=100, verbose_name='Частота')),
                ('duration', models.CharField(blank=True, default='', max_length=100, verbose_name='Длительность')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='Указания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_medicines', to='patients.doctor', verbose_name='Врач')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicine', verbose_name='Препарат')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_medicines', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Активный препарат пациента',
                'verbose_name_plural': 'Активные препараты пациента',
                'unique_together': {('patient', 'doctor', 'medicine')},
            },
        ),
        migrations.DeleteModel(
            name='PatientMedicine',
        ),
    ]
